# PyTorch Fundamentals

## 1. Matrices


### Matrices Brief Introduction
- Basic definition: rectangular array of numbers.
- Tensors (PyTorch)
- Ndarrays (NumPy)

In [12]:
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot

### 1.1 Creating Matrices

In [2]:
import numpy as np

In [4]:
# Creating a 2x2 array
arr = [[1, 2], [3, 4]]
# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [5]:
import torch

In [8]:
# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

### 1.2 Create Matrices with Default Values

In [9]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [10]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [11]:
np.random.rand(2, 2)

array([[0.08192606, 0.86875229],
       [0.43085506, 0.68010487]])

In [12]:
torch.rand(2, 2)

tensor([[0.7289, 0.7183],
        [0.9766, 0.5754]])

### 1.3 Seeds for Reproducibility

In [13]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [14]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

**Seed for GPU is different for now...**

In [18]:
print(torch.cuda.is_available())

True


In [19]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

### 1.3 NumPy and Torch Bridge

### NumPy to Torch 

In [20]:
# Numpy array
np_array = np.ones((2, 2))
print(np_array)
print(type(np_array))

[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


In [23]:
# Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)
print(type(torch_tensor))

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
<class 'torch.Tensor'>


In [24]:
# Data types matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.int8)
## torch.from_numpy(np_array_new) # torch don't have int8 data type

**The conversion supports:**
1. `double`
2. `float` 
3. `int64`, `int32`, `uint8` 

In [25]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int64)
print(torch.from_numpy(np_array_new))

np_array_new = np.ones((2, 2), dtype=np.int32)
print(torch.from_numpy(np_array_new))

# Data types matter
np_array_new = np.ones((2, 2), dtype=np.uint8)
print(torch.from_numpy(np_array_new))

tensor([[1, 1],
        [1, 1]])
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)


In [26]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [27]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]])

In [28]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

**Summary**
<br />These things don't matter much now. But later when you see error messages that require these particular tensor types, refer to this guide!

| NumPy Array Type        | Torch Tensor Type           |
| :-------------: |:--------------:|
| int64     | LongTensor |
| int32     | IntegerTensor |
| uint8      | ByteTensor      |
| float64 | DoubleTensor     |
| float32 | FloatTensor      |
| double | DoubleTensor      |

### Torch to NumPy

In [29]:
torch_tensor = torch.ones(2, 2)
print(type(torch_tensor))

torch_to_numpy = torch_tensor.numpy()
print(type(torch_to_numpy))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


### 1.4 Tensors on CPU vs GPU

In [33]:
# CPU
tensor_cpu = torch.ones(2, 2)

In [31]:
# CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [34]:
# you can also do this 
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)
tensor_cpu.to(device)

cuda:0


tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [35]:
# GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

### 1.5 Tensor Operations

### Resizing Tensor

In [36]:
a = torch.ones(2, 2)
print(a)
print(a.size())

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])


In [41]:
## reshape to [4]
print(a.view(4))
print(a.view(4).size())

tensor([1., 1., 1., 1.])
torch.Size([4])


In [43]:
## reshape to [4,1]
print(a.view([4,1]))
print(a.view([4,1]).size())

tensor([[1.],
        [1.],
        [1.],
        [1.]])
torch.Size([4, 1])


### Element-wise Addition

In [45]:
a = torch.ones(2, 2)
b = torch.ones(2, 2)
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [46]:
# Element-wise addition
c = torch.add(a, b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [47]:
# In-place addition
print('Old c tensor')
print(c)

c.add_(a)

print('-'*60)
print('New c tensor')
print(c)

Old c tensor
tensor([[2., 2.],
        [2., 2.]])
------------------------------------------------------------
New c tensor
tensor([[3., 3.],
        [3., 3.]])


### Element-wise multiplication

In [49]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [51]:
a = torch.ones(2, 2)
print(a)
b = torch.ones(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [52]:
a * b

tensor([[1., 1.],
        [1., 1.]])

In [54]:
# Not in-place
print(torch.mul(a, b))

tensor([[1., 1.],
        [1., 1.]])


In [55]:
# In-place
print(a.mul_(b))
print(a)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


### Element-Wise Division

In [56]:
a = torch.ones(2, 2)
b = torch.zeros(2, 2)
b / a
torch.div(b, a)
# Inplace
b.div_(a)

tensor([[0., 0.],
        [0., 0.]])

### Matrix Dot product

In [6]:
X = np.random.random((5, 3))
Y = torch.rand((5, 3))

In [10]:
##numpy 
print(X.T@X)

## torch 
print(Y.t() @ Y)

[[2.13651371 1.34800008 1.61352433]
 [1.34800008 1.39676311 1.18076587]
 [1.61352433 1.18076587 2.18052947]]
tensor([[3.1673, 1.1914, 2.1958],
        [1.1914, 0.7538, 0.5382],
        [2.1958, 0.5382, 1.8073]])


In [14]:
# numpy
inv(X.T @ X)

# torch
torch.inverse(Y.t() @ Y)

tensor([[ 78.7557, -71.3288, -74.4453],
        [-71.3288,  66.2871,  66.9231],
        [-74.4453,  66.9231,  71.0735]])

In [18]:
# Indexing and broadcasting
A = torch.rand([10,10])
A[:,1]  ## slice just like numpy

tensor([0.8694, 0.7383, 0.6687, 0.1169, 0.1058, 0.3982, 0.5669, 0.9929, 0.9416,
        0.0736])

### Tensor Mean

- $1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55$
- $mean = 55 /10 = 5.5$


In [58]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a.mean(dim=0))
# print(a.mean(dim=1)) this will be an error as there is no rows

tensor(5.5000)


In [59]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
print(a.mean(dim=1))

tensor([5.5000, 5.5000])


## Tensor Standard Deviation

In [60]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)

tensor(3.0277)